/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package pelu_vistas;

import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectOutputStream;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import pelu_modelo.Pelu_Modelo;
import pelu_modelo.Usuario;

/**
 *
 * @author stefa
 */
public class JDialogPeluqueria extends javax.swing.JDialog {

	/**
	 * Creates new form JDialogPeluqueria
	 */
	public JDialogPeluqueria(java.awt.Frame parent, boolean modal) {
		super(parent, modal);
		initComponents();
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
        // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
        private void initComponents() {

                jPanel1 = new javax.swing.JPanel();
                jLabel1 = new javax.swing.JLabel();
                jPanel2 = new javax.swing.JPanel();
                jPanel3 = new javax.swing.JPanel();
                jPanel4 = new javax.swing.JPanel();
                jPanel5 = new javax.swing.JPanel();
                jLabel2 = new javax.swing.JLabel();
                jLabel3 = new javax.swing.JLabel();
                txtNombre = new javax.swing.JTextField();
                txtApellidos = new javax.swing.JTextField();
                btnRegistrar = new javax.swing.JButton();
                jScrollPane1 = new javax.swing.JScrollPane();
                txtArea = new javax.swing.JTextArea();

                jPanel1.setLayout(new java.awt.CardLayout());

                jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
                jLabel1.setText("                                Ver Clientes");
                jPanel1.add(jLabel1, "card2");

                getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_START);

                javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
                jPanel2.setLayout(jPanel2Layout);
                jPanel2Layout.setHorizontalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 549, Short.MAX_VALUE)
                );
                jPanel2Layout.setVerticalGroup(
                        jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );

                getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_END);

                javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
                jPanel3.setLayout(jPanel3Layout);
                jPanel3Layout.setHorizontalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );
                jPanel3Layout.setVerticalGroup(
                        jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 269, Short.MAX_VALUE)
                );

                getContentPane().add(jPanel3, java.awt.BorderLayout.LINE_START);

                javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
                jPanel4.setLayout(jPanel4Layout);
                jPanel4Layout.setHorizontalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 100, Short.MAX_VALUE)
                );
                jPanel4Layout.setVerticalGroup(
                        jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGap(0, 269, Short.MAX_VALUE)
                );

                getContentPane().add(jPanel4, java.awt.BorderLayout.LINE_END);

                jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

                jLabel2.setText("Nombre");
                jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 30, 70, 20));

                jLabel3.setText("Apellidos");
                jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 80, 20));
                jPanel5.add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 110, -1));
                jPanel5.add(txtApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, 110, -1));

                btnRegistrar.setText("Registrar");
                btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
                        public void actionPerformed(java.awt.event.ActionEvent evt) {
                                btnRegistrarActionPerformed(evt);
                        }
                });
                jPanel5.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, -1, -1));

                txtArea.setColumns(20);
                txtArea.setRows(5);
                txtArea.setBorder(javax.swing.BorderFactory.createTitledBorder("Usuarios"));
                jScrollPane1.setViewportView(txtArea);

                jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 320, 70));

                getContentPane().add(jPanel5, java.awt.BorderLayout.CENTER);

                pack();
        }// </editor-fold>//GEN-END:initComponents

        private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
                 
		Usuario miUsuario= new Usuario();
		Pelu_Modelo p = new Pelu_Modelo();
		String nombre,apellido;
		
		
		
		
		nombre=txtNombre.getText();
		apellido=txtApellidos.getText();
		
		miUsuario= new Usuario(nombre, apellido);
		 p.agregarUsuario(miUsuario);
		 
		 txtArea.setText(p.mostrarUsuariosString());
        }//GEN-LAST:event_btnRegistrarActionPerformed

	/**
	 * @param args the command line arguments
	 */
	

        // Variables declaration - do not modify//GEN-BEGIN:variables
        private javax.swing.JButton btnRegistrar;
        private javax.swing.JLabel jLabel1;
        private javax.swing.JLabel jLabel2;
        private javax.swing.JLabel jLabel3;
        private javax.swing.JPanel jPanel1;
        private javax.swing.JPanel jPanel2;
        private javax.swing.JPanel jPanel3;
        private javax.swing.JPanel jPanel4;
        private javax.swing.JPanel jPanel5;
        private javax.swing.JScrollPane jScrollPane1;
        private javax.swing.JTextField txtApellidos;
        private javax.swing.JTextArea txtArea;
        private javax.swing.JTextField txtNombre;
        // End of variables declaration//GEN-END:variables
}
